# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Auto-Doc

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy to staging
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build tardieu_dorian_pendu/MainWindow.xaml.cs
      
      - name: Generate Documentation
        run: dotnet doc tardieu_dorian_pendu/MainWindow.xaml.cs -o documentation
      
      - name: Commit Documentation
        run: 
          git add documentation
          git commit -m "Update documentation"
   
      - name: Push Changes
        uses: ad-m/github-push-action@v0.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

